In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow as tf

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
print(tf.__version__)

2.12.0


# **Use `shift+tab` to view a function's docstring!!!**

## [tf.constant](https://www.tensorflow.org/api_docs/python/tf/constant)

In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Num of dimensions
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Vector dim
vector.ndim

1

In [7]:
# Create a matrix (more than 1 dimension)
matrix = tf.constant([[10, 7],
                      [7, 10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [8]:
matrix.ndim

2

In [9]:
another_matrix = tf.constant([[10., 7.],
                              [7., 10.],
                              [8., 9.]], dtype=tf.float16)
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 8.,  9.]], dtype=float16)>

In [10]:
another_matrix.ndim

2

In [11]:
tensor = tf.constant([[[1, 2, 3], [1, 2, 3]]])

tensor

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [1, 2, 3]]], dtype=int32)>

In [12]:
tensor.ndim

3

- scalar = single number
- vector = 1 dim array
- matrix = 2 dim array
- tensor = n dim array

# Creating Tensors with tf.Variable()
[tf.Variable](https://www.tensorflow.org/api_docs/python/tf/Variable)

In [13]:
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [14]:
# changeable_tensor[0] = 7
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [15]:
# Use .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [16]:
# Doesn't work with unchangeable
# unchangeable_tensor[0].assign(7)
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

^ difference between changeable tensors vs unchangeable tensors

Usually tensorflow does it for you. If you need to create tensors, make constant unless need variability

# Random tensors

- https://www.tensorflow.org/api_docs/python/tf/random/Generator
- https://www.tensorflow.org/api_docs/python/tf/random/uniform

In [17]:
random_1 = tf.random.Generator.from_seed(22)
random_1 = random_1.normal(shape=(3, 2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7531523 ,  2.0261486 ],
       [-0.06997604,  0.85445154],
       [ 0.1175475 ,  0.03493892]], dtype=float32)>

# Shuffle the order of a tensor
Eg. the input is first 5000 ramen, second 5000 spaghetti, and you want to randomize the order of the inputs
- [tf.random.shuffle](https://www.tensorflow.org/api_docs/python/tf/random/shuffle)
- [tf.random.set_seed](https://www.tensorflow.org/api_docs/python/tf/random/set_seed)


In [18]:
not_shuffled = tf.constant([[10, 7],
                           [3, 4],
                           [2, 5]])
not_shuffled.ndim

2

In [19]:
# Shuffle our tensor along the first dimension. Returns a new tensor
# doesn't shuffle in place

tf.random.set_seed(42)  # sets global seed
tf.random.shuffle(not_shuffled, seed=42)  # sets operation seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

# Other ways to make tensors

In [20]:
# Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [21]:
# Create a tensor of all zeros
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

The difference between numpy arrays and tensorflow tensors is that tensors can be run on a GPU

Variable naming:
- X = tf.constant(some_matrix)  # capital for matrix or tensor
- y = tf.constant(vector) # lower case for vector

In [22]:
# Turn numpy arrays into tensors
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [23]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

# Getting information from tensors

- Shape: [tensor.shape](https://www.tensorflow.org/api_docs/python/tf/shape) The length (number of elements) of each of the dimensions of a tensor
- Rank: [tensor.rank](https://www.tensorflow.org/api_docs/python/tf/rank) The number of tensor dimensions. Scalar has rank 0, a vector has rank 1, etc.
- Axis or dimension: [Indexing](https://www.tensorflow.org/guide/tensor#indexing) 
  - TensorFlow follows standard Python indexing rules, similar to indexing a list or a string in Python, and the basic rules for NumPy indexing.
    - indexes start at 0
    - negative indices count backwards from the end
    - colons, :, are used for slices: start:stop:step
- Size: [tf.size](https://www.tensorflow.org/api_docs/python/tf/size) Number of elements in a tensor

In [24]:
# Create a rank 4 tensor
rank_4_tensor = tf.zeros(shape=(2, 3, 4, 5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
rank_4_tensor[0][1]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [26]:
rank_4_tensor.shape, tf.rank(rank_4_tensor), tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]),
 <tf.Tensor: shape=(), dtype=int32, numpy=4>,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [27]:
rank_4_tensor.dtype

tf.float32

In [28]:
# Convert to numpy with .numpy()
print("Shape is:", tf.shape(rank_4_tensor).numpy())
print("Rank is:", tf.rank(rank_4_tensor).numpy())
print("Size is:", tf.size(rank_4_tensor).numpy())

Shape is: [2 3 4 5]
Rank is: 4
Size is: 120


[tf.newaxis](https://www.tensorflow.org/api_docs/python/tf/Tensor#some_useful_examples)

In [29]:
# Add extra dimension with tf.newaxis
rank_4_tensor = rank_4_tensor[..., tf.newaxis]
# rank_4_tensor

Alternative to tf.newaxis
- [tf.expand_dims](https://www.tensorflow.org/api_docs/python/tf/expand_dims)

In [30]:
rank_4_tensor = tf.expand_dims(rank_4_tensor, axis=-1)  # -1 means expand final axis. 0 would expand 0-axis, etc
# returns a new tensor, not inplace
rank_4_tensor.shape

TensorShape([2, 3, 4, 5, 1, 1])

# Manipulating tensors

**basic operations**
+, -, *, /

In [31]:
tensor = tf.constant([[10, 7], 
                      [3, 4]])
tensor + 10  # returns new tensor, original is unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [32]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [33]:
tensor - 1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 6],
       [2, 3]], dtype=int32)>

In [34]:
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5. , 3.5],
       [1.5, 2. ]])>

Built in functions:
- [tf.math](https://www.tensorflow.org/api_docs/python/tf/math) module

Faster with GPU

In [35]:
# Can use tensorflow builtin functions too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

Matrix multiplication
- dot product
- [tf.linalg.matmul](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul)

In [36]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [37]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [38]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [39]:
# matrix multiplication of different shapes
X = tf.constant([[1, 2],
                [3, 4],
                [5, 6]])

Y = tf.constant([[5, 6],
                [7, 8],
                [5, 6]])

# X @ Y incompatible shape
# need to fulfil rules of matrix multiplication

Rules of matrix multiplication:
1. The inner dimensions must match
2. The resulting matrix has the shape of the outer dimensions

www.matrixmultiplication.xyz

In [40]:
# reshape with tf.reshape

X @ tf.reshape(Y, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[21, 16, 19],
       [47, 38, 45],
       [73, 60, 71]], dtype=int32)>

In [41]:
# Or change shape of X instead of y
tf.matmul(tf.reshape(X, shape=(2, 3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 34,  40],
       [ 85, 100]], dtype=int32)>

- [tf.reshape](https://www.tensorflow.org/api_docs/python/tf/reshape)
- [tf.transpose](https://www.tensorflow.org/api_docs/python/tf/transpose) transposes a tensor; turns all rows into columns and columns into rows

In [42]:
# Can do the same with transpose
tf.transpose(X) @ Y

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[51, 60],
       [68, 80]], dtype=int32)>

In [43]:
# reshape keeps element order, while transpose keeps (flips) axes?
X, tf.transpose(X), tf.reshape(X, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

# The dot product. Matrix multiplication is also reffered to as the dot product.
# You can perform matrix multiplication using:
- tf.matmul()
- [tf.tensordot()](https://www.tensorflow.org/api_docs/python/tf/tensordot)



In [44]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[5, 6],
        [7, 8],
        [5, 6]], dtype=int32)>)

In [45]:
# Peform dot product on X and Y, required X or Y to be transposed or reshaped
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[51, 60],
       [68, 80]], dtype=int32)>

## I don't feel like taking more notes
## Here's more tf functions to look up
- generally when performing matrix multiplication on two tensors and one of the axes doesn't line up, use transpose
- generally use tf.matmul()
- tf.cast() to change dtype, ie reduce precision. Use dtype= param

## Aggregating tensors = condensing them from multiple values down to a smaller amount of values

- tf.abs() absolute
- tf.reduce_min() minimum
- tf.reduce_max()
- tf.reduce_mean()
- tf.reduce_sum()

variance
- import tensorflow_probability as tfp
- tfp.stats.variance()

or
- tf.math.reduce_variance()

std, needs float32 or float64 dtype
- tf.math.reduce_std()

positional maximum or minimum
- tf.argmax() index
- tf.reduce_max() value
- tf.argmin() index
- tf.reduce_min() value

In [46]:
tf.reduce_min(tf.constant([1, 2, 3]))

<tf.Tensor: shape=(), dtype=int32, numpy=1>

# Squeezing a tensor
removing all single dimensions

take shape=(1, 1, 1, 1, 50) -> shape(50,)
- tf.squeeze()

In [47]:
tf.squeeze(tf.random.uniform(shape=(1, 1, 1, 1, 50)))

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

# One hot encoding tensors

One hot encoding is a method used to represent categorical data as binary vectors. For each unique category value, it creates a new binary column, where the presence of the category is marked by a "1" and its absence by a "0". For example, for a color column with values "red," "green," and "blue," one hot encoding would create three separate columns, each representing one color with "1"s and "0"s.

In [48]:
# Create a list of indices
some_list = [0, 1, 2, 3]  # could represent colors, like red, green blue, purple

# One hot encode our list of indices
# use tf.one_hot()
tf.one_hot(some_list, depth=len(some_list))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [49]:
# Specify custom values
# generally 1 and 0 are good though
tf.one_hot(some_list, depth=4, on_value="it's on", off_value="potato")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b"it's on", b'potato', b'potato', b'potato'],
       [b'potato', b"it's on", b'potato', b'potato'],
       [b'potato', b'potato', b"it's on", b'potato'],
       [b'potato', b'potato', b'potato', b"it's on"]], dtype=object)>

# More tensor math operations
- tf.square()
- tf.sqrt() must be a float type (use tf.cast())
- tf.math.log()

In [50]:
tf.math.log(tf.random.normal(shape=(3, 2), dtype=tf.float32))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-2.4742684 ,         nan],
       [-0.9725356 ,         nan],
       [        nan, -0.48155943]], dtype=float32)>

# Tensorflow + NumPy

- works with numpy arrays
- np.array() can go into tf.constant(), and vice versa
- or use tf.Tensor.numpy()

default types - dtype
- creating a tensor from np array floats is tf.float64
- creating a tensor from a list of floats is tf.float32

**tensorflow tensors run faster on GPUs than np arrays**

## How to GPU
- tf.test.is_gpu_available()
- tf.config.list_physical_devices()

In [51]:
tf.config.list_physical_devices()
tf.config.list_physical_devices("GPU")  # empty list, unless GPU accelerator is on

[]

In [53]:
# works if GPU accelerator is on

!nvidia-smi

/bin/bash: nvidia-smi: command not found
