---

### 🛠 00. TensorFlow Fundamentals Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

### 📖 00. TensorFlow Fundamentals Extra-curriculum 

* Read through the [list of TensorFlow Python APIs](https://www.tensorflow.org/api_docs/python/), pick one we haven't gone through in this notebook, reverse engineer it (write out the documentation code for yourself) and figure out what it does.
* Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
  * How would you calculate your grocery bill for the month and for the year using tensors?
* Go through the [TensorFlow 2.x quick start for beginners](https://www.tensorflow.org/tutorials/quickstart/beginner) tutorial (be sure to type out all of the code yourself, even if you don't understand it).
  * Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?
* Watch the video ["What's a tensor?"](https://www.youtube.com/watch?v=f5liqUk0ZTw) - a great visual introduction to many of the concepts we've covered in this notebook.

---

In [14]:
import tensorflow as tf

In [2]:
!nvidia-smi

Sun Oct 29 23:00:39 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.06              Driver Version: 545.23.06    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        On  | 00000000:2D:00.0  On |                  N/A |
| 50%   41C    P3              71W / 350W |   2965MiB / 24576MiB |     16%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [15]:
tf.config.list_physical_devices('GPU')

[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [16]:
scalar_01 = tf.constant(5)
vector_01 = tf.constant([1, 2, 3, 4, 5])
matrix_01 = tf.constant([[10, 7],
                         [7, 10]])
tensor_01 = tf.zeros(shape=(2, 2, 3))

answers = (scalar_01, vector_01, matrix_01, tensor_01)

answers

(<tf.Tensor: shape=(), dtype=int32, numpy=5>,
 <tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 7, 10]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
 array([[[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]]], dtype=float32)>)

2. Find the shape, rank and size of the tensors you created in 1.

In [5]:
for tensor in answers:
    print(tensor.shape)
    print(tf.rank(tensor))
    print(tf.size(tensor))

()
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
(5,)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
(2, 2)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
(2, 2, 3)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)


3. Create two tensors containing random values between 0 and 1 with shape [5, 300].

In [6]:
random_tensor_01 = tf.random.uniform(shape=(5, 300), minval=0, maxval=1)
random_tensor_02 = tf.random.uniform(shape=(5, 300), minval=0, maxval=1)

random_tensor_01, random_tensor_02

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.7962116 , 0.14079475, 0.04625666, ..., 0.46693754, 0.6558684 ,
         0.9754741 ],
        [0.19544446, 0.78011906, 0.06618941, ..., 0.4915011 , 0.2111777 ,
         0.6190413 ],
        [0.4374094 , 0.09961832, 0.47195923, ..., 0.2071892 , 0.4846748 ,
         0.39353335],
        [0.5112809 , 0.27877796, 0.04785609, ..., 0.6990696 , 0.03999877,
         0.94319654],
        [0.04121399, 0.4113679 , 0.4256376 , ..., 0.4544165 , 0.82229173,
         0.36876142]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6974325 , 0.7479527 , 0.62313163, ..., 0.07813537, 0.02333331,
         0.6307156 ],
        [0.64180124, 0.8849374 , 0.32016838, ..., 0.528677  , 0.61429775,
         0.7456882 ],
        [0.48119926, 0.8825723 , 0.40920782, ..., 0.2702495 , 0.64606047,
         0.432423  ],
        [0.74189043, 0.72890687, 0.1887244 , ..., 0.15211701, 0.19716275,
         0.48802316],
        [0.58802

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [7]:
dot_product_01 = tf.matmul(random_tensor_01, tf.transpose(random_tensor_02))

dot_product_01

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[78.61671 , 77.71268 , 72.573685, 77.06833 , 78.841156],
       [70.9417  , 70.29974 , 69.630646, 71.3211  , 73.451324],
       [76.28602 , 74.69108 , 72.62325 , 73.1176  , 75.93769 ],
       [71.93382 , 70.54393 , 68.951546, 72.00545 , 75.25865 ],
       [74.14223 , 71.135086, 69.155716, 73.812294, 77.47935 ]],
      dtype=float32)>

5. Multiply the two tensors you created in 3 using dot product.

In [8]:
dot_product_02 = tf.tensordot(tf.transpose(random_tensor_01), random_tensor_02, axes=1)

dot_product_02

<tf.Tensor: shape=(300, 300), dtype=float32, numpy=
array([[1.2947708 , 1.5341767 , 0.84590137, ..., 0.39898437, 0.5508441 ,
        1.0998377 ],
       [1.095531  , 1.1563617 , 0.5476515 , ..., 0.8666679 , 0.8893579 ,
        0.981918  ],
       [0.58763856, 0.6165791 , 0.372999  , ..., 0.560311  , 0.653586  ,
        0.44282398],
       ...,
       [1.5266453 , 1.5534654 , 0.7940331 , ..., 0.87169844, 0.9021223 ,
        1.2378715 ],
       [1.3393884 , 1.2734258 , 0.9156034 , ..., 1.0473697 , 1.0407813 ,
        1.0646285 ],
       [2.1835873 , 2.374613  , 1.2497647 , ..., 0.988501  , 1.1009899 ,
        1.8258979 ]], dtype=float32)>

6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [9]:
random_tensor_03 = tf.random.uniform(shape=(224, 224, 3), minval=0, maxval=1)

random_tensor_03

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.26375663, 0.51208544, 0.21757865],
        [0.97420764, 0.48251224, 0.00708532],
        [0.6764189 , 0.5316    , 0.09499872],
        ...,
        [0.52048266, 0.698071  , 0.01401687],
        [0.91233397, 0.5432066 , 0.53939235],
        [0.9756377 , 0.7094623 , 0.03899431]],

       [[0.04614389, 0.783525  , 0.62092733],
        [0.29305816, 0.29939878, 0.15268123],
        [0.14554   , 0.44827163, 0.36666048],
        ...,
        [0.8384006 , 0.6293851 , 0.96330893],
        [0.60787237, 0.29178762, 0.8522928 ],
        [0.736212  , 0.9671091 , 0.5391029 ]],

       [[0.7084861 , 0.0446198 , 0.51553214],
        [0.53163886, 0.48366272, 0.22268164],
        [0.69417334, 0.09922671, 0.14841068],
        ...,
        [0.21158993, 0.61080253, 0.08681905],
        [0.8490685 , 0.5721718 , 0.55555224],
        [0.06996667, 0.0745759 , 0.8072742 ]],

       ...,

       [[0.6782018 , 0.03237796, 0.07120264],
        [0.73

7. Find the min and max values of the tensor you created in 6 along the first axis.

In [10]:
min_01 = tf.math.reduce_min(random_tensor_03, axis=0)
max_01 = tf.math.reduce_max(random_tensor_03, axis=0)

min_01, max_01

(<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
 array([[1.58786774e-04, 2.12395191e-03, 3.48758698e-03],
        [3.84688377e-04, 6.39569759e-03, 2.55501270e-03],
        [6.99138641e-03, 2.32601166e-03, 8.17179680e-04],
        [7.50923157e-03, 1.00469589e-03, 9.04726982e-03],
        [1.51493549e-02, 1.93238258e-04, 1.24764442e-03],
        [8.35418701e-04, 3.35133076e-03, 1.37078762e-02],
        [2.14600563e-03, 4.11677361e-03, 9.90605354e-03],
        [5.94377518e-04, 1.64269209e-02, 4.53579426e-03],
        [8.77463818e-03, 1.85477734e-03, 7.97748566e-04],
        [1.12683773e-02, 5.85997105e-03, 8.67831707e-03],
        [1.68454647e-03, 1.96933746e-03, 7.58767128e-04],
        [9.24050808e-03, 1.94418430e-03, 9.17673111e-04],
        [5.40733337e-03, 2.18558311e-03, 4.34696674e-03],
        [4.19366360e-03, 3.28958035e-03, 9.82964039e-03],
        [3.54862213e-03, 8.55565071e-04, 1.00123882e-03],
        [7.11154938e-03, 2.03847885e-05, 8.30316544e-03],
        [2.36725807e-

8. Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [11]:
random_tensor_04 = tf.random.uniform(shape=(1, 224, 224, 3))
random_tensor_04 = tf.squeeze(random_tensor_04)

random_tensor_04

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.33908117, 0.07490909, 0.76528144],
        [0.3244021 , 0.01873457, 0.22276306],
        [0.00790358, 0.49571586, 0.71706975],
        ...,
        [0.14985204, 0.22814167, 0.66214144],
        [0.32430017, 0.8355987 , 0.53877497],
        [0.8749969 , 0.4464395 , 0.02150381]],

       [[0.12684894, 0.5633377 , 0.84591234],
        [0.7079605 , 0.07423198, 0.96901166],
        [0.29139376, 0.7102579 , 0.79102206],
        ...,
        [0.84914815, 0.6310123 , 0.01643264],
        [0.67456627, 0.35830617, 0.36971927],
        [0.82121766, 0.36880565, 0.16071522]],

       [[0.8292507 , 0.57361066, 0.65713084],
        [0.05604529, 0.9647949 , 0.75714624],
        [0.48065114, 0.37121916, 0.6251197 ],
        ...,
        [0.69061136, 0.20795739, 0.34024203],
        [0.74492645, 0.7408279 , 0.6878493 ],
        [0.64753866, 0.72664   , 0.6768408 ]],

       ...,

       [[0.2080636 , 0.7054635 , 0.26175308],
        [0.57

9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [12]:
random_tensor_05 = tf.random.uniform(shape=(10,), minval=1, maxval=20, dtype=tf.int32)
max_val_index = tf.argmax(random_tensor_05)

max_val_index, random_tensor_05

(<tf.Tensor: shape=(), dtype=int64, numpy=3>,
 <tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 1,  5, 14, 19, 15, 11, 10, 13,  3,  7], dtype=int32)>)

10. One-hot encode the tensor you created in 9.

In [13]:
one_hot_01 = tf.one_hot(random_tensor_05, depth=len(random_tensor_05))

one_hot_01

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]], dtype=float32)>